//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EducacionVial.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EducacionVial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ejemplo_xd {
            get {
                object obj = ResourceManager.GetObject("Ejemplo xd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Ejemplo_xd2 {
            get {
                object obj = ResourceManager.GetObject("Ejemplo xd2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mostrar_solo_para_ingresar_el_nombre_de_usuario_y_luego_de_poner_un_usuario_existente__aparecer_el_cuadrito_donde_se_agrega_la_contraseña {
            get {
                object obj = ResourceManager.GetObject("Mostrar solo para ingresar el nombre de usuario y luego de poner un usuario exist" +
                        "ente, aparecer el cuadrito donde se agrega la contraseña", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mostrar_solo_para_ingresar_el_nombre_de_usuario_y_luego_de_poner_un_usuario_existente__aparecer_el_cuadrito_donde_se_agrega_la_contraseña__1_ {
            get {
                object obj = ResourceManager.GetObject("Mostrar solo para ingresar el nombre de usuario y luego de poner un usuario exist" +
                        "ente, aparecer el cuadrito donde se agrega la contraseña (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mostrar_solo_para_ingresar_el_nombre_de_usuario_y_luego_de_poner_un_usuario_existente__aparecer_el_cuadrito_donde_se_agrega_la_contraseña__2_ {
            get {
                object obj = ResourceManager.GetObject("Mostrar solo para ingresar el nombre de usuario y luego de poner un usuario exist" +
                        "ente, aparecer el cuadrito donde se agrega la contraseña (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mostrar_solo_para_ingresar_el_nombre_de_usuario_y_luego_de_poner_un_usuario_existente__aparecer_el_cuadrito_donde_se_agrega_la_contraseña__3_ {
            get {
                object obj = ResourceManager.GetObject("Mostrar solo para ingresar el nombre de usuario y luego de poner un usuario exist" +
                        "ente, aparecer el cuadrito donde se agrega la contraseña (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mostrar_solo_para_ingresar_el_nombre_de_usuario_y_luego_de_poner_un_usuario_existente__aparecer_el_cuadrito_donde_se_agrega_la_contraseña__4_ {
            get {
                object obj = ResourceManager.GetObject("Mostrar solo para ingresar el nombre de usuario y luego de poner un usuario exist" +
                        "ente, aparecer el cuadrito donde se agrega la contraseña (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap parte_de_arribapng {
            get {
                object obj = ResourceManager.GetObject("parte de arribapng", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PROYECT_VIAL {
            get {
                object obj = ResourceManager.GetObject("PROYECT-VIAL", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PROYECT_VIAL__1_ {
            get {
                object obj = ResourceManager.GetObject("PROYECT-VIAL (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PROYECT_VIAL__2_ {
            get {
                object obj = ResourceManager.GetObject("PROYECT-VIAL (2)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PROYECT_VIAL__3_ {
            get {
                object obj = ResourceManager.GetObject("PROYECT-VIAL (3)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PROYECT_VIAL__4_ {
            get {
                object obj = ResourceManager.GetObject("PROYECT-VIAL (4)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Salida {
            get {
                object obj = ResourceManager.GetObject("Salida", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
